language: node_js
node_js:
- '0.12'
install: npm install
script: npm run build
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&

  eval key=\$encrypted_3ba9e9396f43_key &&
  eval iv=\$encrypted_3ba9e9396f43_iv &&

  mkdir -p ~/.ssh &&
  openssl aes-256-cbc -K $key -iv $iv -in id_rsa.enc -out ~/.ssh/id_rsa -d &&
  chmod 600 ~/.ssh/id_rsa &&

  git clone --branch gh-pages git@github.com:globin/drinkup-built deploy_docs &&

  cd deploy_docs &&
  git config user.name "upload bot" &&
  git config user.email "nobody@example.com" &&
  rm -rf * &&
  cp -R ../tmp/* . &&
  echo drinkup.glob.in > CNAME &&
  git add -A . &&
  git commit -qm "built upload for drinkup ($TRAVIS_REPO_SLUG)" &&
  git push -q origin gh-pages

